version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            python --version
            pip install -q platformio --user
            echo 'export PATH=~/.local/bin:$PATH' >> $BASH_ENV
      
      - run:
          name: Build Application
          command: |
            platformio ci --project-conf platformio.ini
          environment:
            PLATFORMIO_CI_SRC: src

workflows:
  main:
    jobs:
      - build
